# Generated by Django 3.2.5 on 2023-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32, verbose_name='資產編號')),
                ('form', models.CharField(max_length=32, verbose_name='資產類別')),
                ('name', models.CharField(max_length=32, verbose_name='名稱')),
                ('style', models.CharField(max_length=32, verbose_name='規格')),
                ('nums', models.CharField(max_length=32, verbose_name='數量')),
                ('unit', models.CharField(max_length=32, verbose_name='單位')),
                ('put_place', models.CharField(max_length=32, verbose_name='放置地點')),
                ('price', models.CharField(max_length=32, verbose_name='財產價值')),
                ('dept', models.CharField(max_length=32, verbose_name='財產部門')),
                ('syid', models.CharField(max_length=32, verbose_name='員編(保管人)')),
                ('buydate', models.DateTimeField(verbose_name='購置日期')),
                ('chgdate', models.DateTimeField(verbose_name='異動日期')),
                ('memo', models.CharField(max_length=32, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_no', models.CharField(max_length=32, verbose_name='移轉單號')),
                ('createDate', models.DateTimeField(verbose_name='建立日')),
                ('moveDate', models.DateTimeField(verbose_name='移轉日')),
                ('createNo', models.CharField(max_length=32, verbose_name='員編(建立者)')),
                ('moveToDept', models.CharField(max_length=32, verbose_name='轉出部門')),
                ('moveToSyId', models.CharField(max_length=32, verbose_name='轉出員編')),
                ('moveToAssetNo', models.CharField(max_length=32, verbose_name='轉出資產編號')),
                ('moveToNums', models.CharField(max_length=32, verbose_name='轉出數量')),
                ('moveInDept', models.CharField(max_length=32, verbose_name='轉入部門')),
                ('moveInSyId', models.CharField(max_length=32, verbose_name='轉入員編')),
                ('moveInAssetNo', models.CharField(max_length=32, verbose_name='轉入資產編號')),
                ('moveInNums', models.CharField(max_length=32, verbose_name='轉入數量')),
                ('moveInPlace', models.CharField(max_length=32, verbose_name='轉入放置地點')),
                ('memo', models.CharField(max_length=32, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='SyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syid', models.CharField(max_length=6, verbose_name='系統員編')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('area', models.CharField(max_length=32, verbose_name='所屬區域')),
                ('workunit', models.CharField(max_length=32, verbose_name='所屬單位')),
            ],
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_no', models.CharField(max_length=32, verbose_name='區域編號')),
                ('area_name', models.CharField(max_length=32, verbose_name='區域名稱')),
                ('memo', models.CharField(max_length=32, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=32, verbose_name='編號')),
                ('unit_name', models.CharField(max_length=32, verbose_name='名稱')),
                ('memo', models.CharField(max_length=32, verbose_name='備註')),
            ],
        ),
    ]
