# Generated by Django 3.2.5 on 2023-01-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetbasic',
            table='AssetBasic',
        ),
        migrations.AlterModelTable(
            name='assetmove',
            table='AssetMove',
        ),
        migrations.AlterModelTable(
            name='syuser',
            table='SyUser',
        ),
        migrations.AlterModelTable(
            name='userarea',
            table='UserArea',
        ),
        migrations.AlterModelTable(
            name='userunit',
            table='UserUnit',
        ),
    ]
