# Generated by Django 3.2.5 on 2023-01-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20230109_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syuser',
            options={'verbose_name': '資訊類別', 'verbose_name_plural': '資訊類別'},
        ),
        migrations.AlterModelTable(
            name='syuser',
            table=None,
        ),
    ]
