# Generated by Django 3.2.5 on 2023-01-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20230110_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userunit',
            options={'verbose_name': '所屬單位資料檔', 'verbose_name_plural': '單位資料檔'},
        ),
        migrations.AlterField(
            model_name='syuser',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.userarea', verbose_name='所屬區域'),
        ),
        migrations.AlterField(
            model_name='syuser',
            name='workunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.userunit', verbose_name='所屬單位'),
        ),
    ]
