# Generated by Django 3.2.5 on 2023-01-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20230110_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syuser',
            name='area',
        ),
        migrations.RemoveField(
            model_name='syuser',
            name='workunit',
        ),
    ]
