# Generated by Django 3.2.5 on 2023-01-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20230110_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuser',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.userarea', verbose_name='所屬區域'),
        ),
        migrations.AddField(
            model_name='syuser',
            name='workunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.userunit', verbose_name='所屬單位'),
        ),
    ]
