# Generated by Django 3.2.5 on 2023-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_auto_20230110_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userunit',
            options={'verbose_name': '所屬單位資料檔', 'verbose_name_plural': '所屬單位資料檔'},
        ),
        migrations.AlterField(
            model_name='syuser',
            name='syid',
            field=models.CharField(max_length=6, verbose_name='員編'),
        ),
    ]
