# Generated by Django 3.2.5 on 2023-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20230110_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbasic',
            name='unit',
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='buydate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='購置日期'),
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='form',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='資產類別'),
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='nums',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='財產價值'),
        ),
        migrations.AlterField(
            model_name='assetbasic',
            name='style',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='規格'),
        ),
    ]
